version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mbti_project
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - ./db_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mbti_test
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
      DATABASE_URL: postgres://postgres:postgres@postgres-db:5432/mbti_project
    depends_on:
      - postgres
    restart: unless-stopped
    command: npm run start
